name: gTest
on:
  push:
    branches: [ main, starter, solution ]
  pull_request:
    branches: [ main, starter, solution ]
permissions:
  contents: write
jobs:
  prep_then_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Install script for GTest
      run:  ./install-googletest.sh
    - name: Build + Run the project
      run: ./runit.sh
